import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        {/* Sidebar */}
        <nav className="bg-gray-800 text-white w-16 hover:w-48 transition-all duration-300 h-screen flex flex-col items-start py-4 group">
          {/* Home */}
          <div className="flex items-center w-full px-3 py-2 cursor-pointer hover:bg-gray-700 rounded">
            <span className="text-2xl">🏠</span>
            <span className="ml-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              Home
            </span>
          </div>

          {/* Inventory */}
          <div className="flex items-center w-full px-3 py-2 cursor-pointer hover:bg-gray-700 rounded">
            <span className="text-2xl">📦</span>
            <span className="ml-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              Inventory
            </span>
          </div>

          {/* Settings */}
          <div className="flex items-center w-full px-3 py-2 cursor-pointer hover:bg-gray-700 rounded">
            <span className="text-2xl">⚙️</span>
            <span className="ml-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              Settings
            </span>
          </div>
        </nav>

        {/* Main content */}
        <main className="flex-1 p-8">{children}</main>
      </body>
    </html>
  );
}
